-- MySQL Script generated by MySQL Workbench
-- Fri Nov 10 17:46:07 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_review_movie
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_review_movie
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_review_movie` DEFAULT CHARACTER SET utf8 ;
USE `db_review_movie` ;

-- -----------------------------------------------------
-- Table `db_review_movie`.`profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_review_movie`.`profile` (
  `id` INT NOT NULL,
  `age` INT NOT NULL,
  `biodata` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_review_movie`.`genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_review_movie`.`genre` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_review_movie`.`movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_review_movie`.`movie` (
  `id` INT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `summary` VARCHAR(255) NOT NULL,
  `year` INT NOT NULL,
  `poster` VARCHAR(255) NOT NULL,
  `genre_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_movie_genre1_idx` (`genre_id` ASC) VISIBLE,
  CONSTRAINT `fk_movie_genre1`
    FOREIGN KEY (`genre_id`)
    REFERENCES `db_review_movie`.`genre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_review_movie`.`review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_review_movie`.`review` (
  `id` INT NOT NULL,
  `rating` INT NULL,
  `critics` VARCHAR(255) NULL,
  `movie_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_review_movie1_idx` (`movie_id` ASC) VISIBLE,
  CONSTRAINT `fk_review_movie1`
    FOREIGN KEY (`movie_id`)
    REFERENCES `db_review_movie`.`movie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_review_movie`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_review_movie`.`user` (
  `id` INT NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `profile_id` INT NOT NULL,
  `review_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_profile1_idx` (`profile_id` ASC) VISIBLE,
  INDEX `fk_user_review1_idx` (`review_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_profile1`
    FOREIGN KEY (`profile_id`)
    REFERENCES `db_review_movie`.`profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_review1`
    FOREIGN KEY (`review_id`)
    REFERENCES `db_review_movie`.`review` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_review_movie`.`cast`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_review_movie`.`cast` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `age` VARCHAR(255) NOT NULL,
  `biodata` VARCHAR(255) NOT NULL,
  `movie_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cast_movie1_idx` (`movie_id` ASC) VISIBLE,
  CONSTRAINT `fk_cast_movie1`
    FOREIGN KEY (`movie_id`)
    REFERENCES `db_review_movie`.`movie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_review_movie`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_review_movie`.`role` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `cast_id` INT NOT NULL,
  `movie_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_role_cast1_idx` (`cast_id` ASC) VISIBLE,
  INDEX `fk_role_movie1_idx` (`movie_id` ASC) VISIBLE,
  CONSTRAINT `fk_role_cast1`
    FOREIGN KEY (`cast_id`)
    REFERENCES `db_review_movie`.`cast` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_movie1`
    FOREIGN KEY (`movie_id`)
    REFERENCES `db_review_movie`.`movie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
